databases:
  - name: days_DB
    databaseName: days_db
    user: diary
    region: singapore

services:
  - type: web
    name: diary
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: days_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

